// AUTO-GENERATED by scripts/gen-react-types.mjs — do not edit by hand.
// Run `npm run build` to update after adding or changing components.

export {};
import type { ButtonVariant } from './as-button.js';
import type { IconSize } from './as-icon.js';

type HTMLProps = {
  id?: string;
  class?: string;
  className?: string;
  style?: string | Record<string, string>;
  slot?: string;
  children?: unknown;
  ref?: unknown;
  key?: string | number;
  onClick?: (event: MouseEvent) => void;
  onFocus?: (event: FocusEvent) => void;
  onBlur?: (event: FocusEvent) => void;
  onKeyDown?: (event: KeyboardEvent) => void;
  onKeyUp?: (event: KeyboardEvent) => void;
  onMouseEnter?: (event: MouseEvent) => void;
  onMouseLeave?: (event: MouseEvent) => void;
  [attr: string]: unknown;
};

declare global {
  namespace JSX {
    interface IntrinsicElements {
      'as-button': HTMLProps & {
        'href'?: string;
        'target'?: string;
        'variant'?: ButtonVariant;
        'accent'?: string;
        'disabled'?: boolean;
      };
      'as-icon': HTMLProps & {
        'name'?: string;
        'size'?: IconSize;
        'color'?: string;
        'label'?: string;
        'flip-x'?: boolean;
        'flip-y'?: boolean;
        'rotate'?: string;
        'image'?: boolean;
      };
    }
  }
}
